// ATP Top 30 + WTA Top 20 player data (2025 season)
export const atpPlayers = [
  {
    name: "Jannik Sinner",
    country: "ITA",
    ranking: 1,
    points: 11830,
    age: 23,
    height: "6'2\"",
    plays: "Right-handed",
    titles: 16,
    wonLost: "73-12",
    surfaceWin: '{"hard":0.88,"clay":0.74,"grass":0.82}',
  },
  {
    name: "Alexander Zverev",
    country: "GER",
    ranking: 2,
    points: 8135,
    age: 27,
    height: "6'6\"",
    plays: "Right-handed",
    titles: 23,
    wonLost: "62-16",
    surfaceWin: '{"hard":0.80,"clay":0.82,"grass":0.70}',
  },
  {
    name: "Carlos Alcaraz",
    country: "ESP",
    ranking: 3,
    points: 7010,
    age: 21,
    height: "6'1\"",
    plays: "Right-handed",
    titles: 16,
    wonLost: "58-14",
    surfaceWin: '{"hard":0.82,"clay":0.86,"grass":0.90}',
  },
  {
    name: "Novak Djokovic",
    country: "SRB",
    ranking: 4,
    points: 5900,
    age: 37,
    height: "6'2\"",
    plays: "Right-handed",
    titles: 99,
    wonLost: "45-11",
    surfaceWin: '{"hard":0.87,"clay":0.82,"grass":0.86}',
  },
  {
    name: "Taylor Fritz",
    country: "USA",
    ranking: 5,
    points: 5100,
    age: 27,
    height: "6'5\"",
    plays: "Right-handed",
    titles: 9,
    wonLost: "51-18",
    surfaceWin: '{"hard":0.78,"clay":0.58,"grass":0.72}',
  },
  {
    name: "Daniil Medvedev",
    country: "RUS",
    ranking: 6,
    points: 4870,
    age: 29,
    height: "6'6\"",
    plays: "Right-handed",
    titles: 20,
    wonLost: "48-17",
    surfaceWin: '{"hard":0.82,"clay":0.55,"grass":0.68}',
  },
  {
    name: "Casper Ruud",
    country: "NOR",
    ranking: 7,
    points: 4210,
    age: 26,
    height: "6'0\"",
    plays: "Right-handed",
    titles: 10,
    wonLost: "44-16",
    surfaceWin: '{"hard":0.68,"clay":0.80,"grass":0.58}',
  },
  {
    name: "Alex de Minaur",
    country: "AUS",
    ranking: 8,
    points: 3855,
    age: 25,
    height: "6'0\"",
    plays: "Right-handed",
    titles: 8,
    wonLost: "47-19",
    surfaceWin: '{"hard":0.76,"clay":0.62,"grass":0.74}',
  },
  {
    name: "Andrey Rublev",
    country: "RUS",
    ranking: 9,
    points: 3520,
    age: 27,
    height: "6'2\"",
    plays: "Right-handed",
    titles: 16,
    wonLost: "42-17",
    surfaceWin: '{"hard":0.75,"clay":0.72,"grass":0.62}',
  },
  {
    name: "Grigor Dimitrov",
    country: "BUL",
    ranking: 10,
    points: 3300,
    age: 33,
    height: "6'3\"",
    plays: "Right-handed",
    titles: 9,
    wonLost: "40-15",
    surfaceWin: '{"hard":0.72,"clay":0.65,"grass":0.70}',
  },
  {
    name: "Stefanos Tsitsipas",
    country: "GRE",
    ranking: 11,
    points: 3100,
    age: 26,
    height: "6'4\"",
    plays: "Right-handed",
    titles: 11,
    wonLost: "38-16",
    surfaceWin: '{"hard":0.70,"clay":0.78,"grass":0.62}',
  },
  {
    name: "Tommy Paul",
    country: "USA",
    ranking: 12,
    points: 2900,
    age: 27,
    height: "6'1\"",
    plays: "Right-handed",
    titles: 4,
    wonLost: "39-15",
    surfaceWin: '{"hard":0.72,"clay":0.60,"grass":0.70}',
  },
  {
    name: "Holger Rune",
    country: "DEN",
    ranking: 13,
    points: 2750,
    age: 22,
    height: "6'2\"",
    plays: "Right-handed",
    titles: 6,
    wonLost: "36-15",
    surfaceWin: '{"hard":0.70,"clay":0.72,"grass":0.62}',
  },
  {
    name: "Ben Shelton",
    country: "USA",
    ranking: 14,
    points: 2600,
    age: 22,
    height: "6'4\"",
    plays: "Left-handed",
    titles: 3,
    wonLost: "37-16",
    surfaceWin: '{"hard":0.74,"clay":0.55,"grass":0.68}',
  },
  {
    name: "Hubert Hurkacz",
    country: "POL",
    ranking: 15,
    points: 2450,
    age: 28,
    height: "6'5\"",
    plays: "Right-handed",
    titles: 8,
    wonLost: "35-14",
    surfaceWin: '{"hard":0.72,"clay":0.58,"grass":0.78}',
  },
  {
    name: "Frances Tiafoe",
    country: "USA",
    ranking: 16,
    points: 2300,
    age: 27,
    height: "6'2\"",
    plays: "Right-handed",
    titles: 3,
    wonLost: "33-17",
    surfaceWin: '{"hard":0.70,"clay":0.55,"grass":0.68}',
  },
  {
    name: "Ugo Humbert",
    country: "FRA",
    ranking: 17,
    points: 2200,
    age: 27,
    height: "6'3\"",
    plays: "Left-handed",
    titles: 5,
    wonLost: "34-15",
    surfaceWin: '{"hard":0.68,"clay":0.58,"grass":0.74}',
  },
  {
    name: "Felix Auger-Aliassime",
    country: "CAN",
    ranking: 18,
    points: 2100,
    age: 24,
    height: "6'4\"",
    plays: "Right-handed",
    titles: 4,
    wonLost: "32-16",
    surfaceWin: '{"hard":0.70,"clay":0.60,"grass":0.68}',
  },
  {
    name: "Sebastian Korda",
    country: "USA",
    ranking: 19,
    points: 2000,
    age: 24,
    height: "6'5\"",
    plays: "Right-handed",
    titles: 3,
    wonLost: "30-14",
    surfaceWin: '{"hard":0.68,"clay":0.62,"grass":0.72}',
  },
  {
    name: "Jack Draper",
    country: "GBR",
    ranking: 20,
    points: 1950,
    age: 23,
    height: "6'4\"",
    plays: "Left-handed",
    titles: 3,
    wonLost: "31-13",
    surfaceWin: '{"hard":0.74,"clay":0.58,"grass":0.72}',
  },
];

export const wtaPlayers = [
  {
    name: "Aryna Sabalenka",
    country: "BLR",
    ranking: 1,
    points: 10920,
    age: 26,
    height: "5'11\"",
    plays: "Right-handed",
    titles: 18,
    wonLost: "68-10",
    surfaceWin: '{"hard":0.88,"clay":0.75,"grass":0.78}',
  },
  {
    name: "Iga Swiatek",
    country: "POL",
    ranking: 2,
    points: 8370,
    age: 23,
    height: "5'9\"",
    plays: "Right-handed",
    titles: 22,
    wonLost: "60-12",
    surfaceWin: '{"hard":0.82,"clay":0.92,"grass":0.65}',
  },
  {
    name: "Coco Gauff",
    country: "USA",
    ranking: 3,
    points: 7150,
    age: 21,
    height: "5'10\"",
    plays: "Right-handed",
    titles: 10,
    wonLost: "55-14",
    surfaceWin: '{"hard":0.80,"clay":0.74,"grass":0.72}',
  },
  {
    name: "Jasmine Paolini",
    country: "ITA",
    ranking: 4,
    points: 5900,
    age: 29,
    height: "5'4\"",
    plays: "Right-handed",
    titles: 5,
    wonLost: "48-16",
    surfaceWin: '{"hard":0.72,"clay":0.78,"grass":0.74}',
  },
  {
    name: "Zheng Qinwen",
    country: "CHN",
    ranking: 5,
    points: 5400,
    age: 22,
    height: "5'10\"",
    plays: "Right-handed",
    titles: 4,
    wonLost: "46-15",
    surfaceWin: '{"hard":0.78,"clay":0.68,"grass":0.65}',
  },
  {
    name: "Elena Rybakina",
    country: "KAZ",
    ranking: 6,
    points: 4800,
    age: 25,
    height: "6'0\"",
    plays: "Right-handed",
    titles: 8,
    wonLost: "42-14",
    surfaceWin: '{"hard":0.76,"clay":0.65,"grass":0.85}',
  },
  {
    name: "Jessica Pegula",
    country: "USA",
    ranking: 7,
    points: 4500,
    age: 31,
    height: "5'7\"",
    plays: "Right-handed",
    titles: 6,
    wonLost: "40-16",
    surfaceWin: '{"hard":0.78,"clay":0.62,"grass":0.68}',
  },
  {
    name: "Emma Navarro",
    country: "USA",
    ranking: 8,
    points: 4100,
    age: 23,
    height: "5'6\"",
    plays: "Right-handed",
    titles: 3,
    wonLost: "38-15",
    surfaceWin: '{"hard":0.74,"clay":0.62,"grass":0.70}',
  },
  {
    name: "Daria Kasatkina",
    country: "RUS",
    ranking: 9,
    points: 3800,
    age: 28,
    height: "5'7\"",
    plays: "Right-handed",
    titles: 7,
    wonLost: "36-15",
    surfaceWin: '{"hard":0.70,"clay":0.74,"grass":0.62}',
  },
  {
    name: "Barbora Krejcikova",
    country: "CZE",
    ranking: 10,
    points: 3500,
    age: 29,
    height: "5'11\"",
    plays: "Right-handed",
    titles: 8,
    wonLost: "34-14",
    surfaceWin: '{"hard":0.68,"clay":0.72,"grass":0.78}',
  },
  {
    name: "Ons Jabeur",
    country: "TUN",
    ranking: 11,
    points: 3200,
    age: 30,
    height: "5'6\"",
    plays: "Right-handed",
    titles: 5,
    wonLost: "32-14",
    surfaceWin: '{"hard":0.68,"clay":0.72,"grass":0.80}',
  },
  {
    name: "Madison Keys",
    country: "USA",
    ranking: 12,
    points: 3100,
    age: 30,
    height: "5'10\"",
    plays: "Right-handed",
    titles: 9,
    wonLost: "35-15",
    surfaceWin: '{"hard":0.76,"clay":0.60,"grass":0.72}',
  },
  {
    name: "Paula Badosa",
    country: "ESP",
    ranking: 13,
    points: 2900,
    age: 27,
    height: "5'11\"",
    plays: "Right-handed",
    titles: 5,
    wonLost: "33-16",
    surfaceWin: '{"hard":0.72,"clay":0.70,"grass":0.62}',
  },
  {
    name: "Anna Kalinskaya",
    country: "RUS",
    ranking: 14,
    points: 2750,
    age: 26,
    height: "5'10\"",
    plays: "Right-handed",
    titles: 3,
    wonLost: "30-14",
    surfaceWin: '{"hard":0.74,"clay":0.62,"grass":0.65}',
  },
  {
    name: "Mirra Andreeva",
    country: "RUS",
    ranking: 15,
    points: 2600,
    age: 17,
    height: "5'8\"",
    plays: "Right-handed",
    titles: 2,
    wonLost: "31-13",
    surfaceWin: '{"hard":0.72,"clay":0.74,"grass":0.62}',
  },
];

export const tournaments = [
  {
    name: "Australian Open",
    surface: "Hard",
    location: "Melbourne, Australia",
    tour: "Grand Slam",
    category: "Grand Slam",
    drawSize: 128,
    prize: "$76,500,000",
    startDate: "2026-01-19",
    endDate: "2026-02-01",
  },
  {
    name: "Indian Wells Masters",
    surface: "Hard",
    location: "Indian Wells, USA",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 96,
    prize: "$8,800,000",
    startDate: "2026-03-05",
    endDate: "2026-03-16",
  },
  {
    name: "Miami Open",
    surface: "Hard",
    location: "Miami, USA",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 96,
    prize: "$8,800,000",
    startDate: "2026-03-19",
    endDate: "2026-03-30",
  },
  {
    name: "Monte-Carlo Masters",
    surface: "Clay",
    location: "Monaco",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 56,
    prize: "$5,950,000",
    startDate: "2026-04-06",
    endDate: "2026-04-13",
  },
  {
    name: "Madrid Open",
    surface: "Clay",
    location: "Madrid, Spain",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 56,
    prize: "$7,700,000",
    startDate: "2026-04-27",
    endDate: "2026-05-04",
  },
  {
    name: "Italian Open",
    surface: "Clay",
    location: "Rome, Italy",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 56,
    prize: "$7,700,000",
    startDate: "2026-05-10",
    endDate: "2026-05-18",
  },
  {
    name: "Roland Garros",
    surface: "Clay",
    location: "Paris, France",
    tour: "Grand Slam",
    category: "Grand Slam",
    drawSize: 128,
    prize: "$53,500,000",
    startDate: "2026-05-25",
    endDate: "2026-06-08",
  },
  {
    name: "Wimbledon",
    surface: "Grass",
    location: "London, UK",
    tour: "Grand Slam",
    category: "Grand Slam",
    drawSize: 128,
    prize: "$59,600,000",
    startDate: "2026-06-29",
    endDate: "2026-07-12",
  },
  {
    name: "Canadian Open",
    surface: "Hard",
    location: "Montreal, Canada",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 56,
    prize: "$6,400,000",
    startDate: "2026-08-03",
    endDate: "2026-08-10",
  },
  {
    name: "Cincinnati Masters",
    surface: "Hard",
    location: "Cincinnati, USA",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 56,
    prize: "$6,600,000",
    startDate: "2026-08-11",
    endDate: "2026-08-17",
  },
  {
    name: "US Open",
    surface: "Hard",
    location: "New York, USA",
    tour: "Grand Slam",
    category: "Grand Slam",
    drawSize: 128,
    prize: "$65,000,000",
    startDate: "2026-08-31",
    endDate: "2026-09-13",
  },
  {
    name: "Shanghai Masters",
    surface: "Hard",
    location: "Shanghai, China",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 96,
    prize: "$8,800,000",
    startDate: "2026-10-04",
    endDate: "2026-10-12",
  },
  {
    name: "Paris Masters",
    surface: "Hard",
    location: "Paris, France",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 48,
    prize: "$5,950,000",
    startDate: "2026-10-27",
    endDate: "2026-11-02",
  },
  {
    name: "ATP Finals",
    surface: "Hard",
    location: "Turin, Italy",
    tour: "ATP",
    category: "Masters 1000",
    drawSize: 8,
    prize: "$15,250,000",
    startDate: "2026-11-09",
    endDate: "2026-11-16",
  },
];

// Upcoming matches for the current "season" with realistic matchups
export const upcomingMatches = [
  // Indian Wells Round of 32
  {
    p1: "Jannik Sinner",
    p2: "Tommy Paul",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-10T19:00:00Z",
  },
  {
    p1: "Carlos Alcaraz",
    p2: "Holger Rune",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-10T21:00:00Z",
  },
  {
    p1: "Novak Djokovic",
    p2: "Ben Shelton",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-10T23:00:00Z",
  },
  {
    p1: "Alexander Zverev",
    p2: "Frances Tiafoe",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-11T01:00:00Z",
  },
  {
    p1: "Taylor Fritz",
    p2: "Felix Auger-Aliassime",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-12T19:00:00Z",
  },
  {
    p1: "Daniil Medvedev",
    p2: "Jack Draper",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-12T21:00:00Z",
  },
  {
    p1: "Andrey Rublev",
    p2: "Ugo Humbert",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-12T23:00:00Z",
  },
  {
    p1: "Grigor Dimitrov",
    p2: "Sebastian Korda",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "ATP",
    startTime: "2026-03-13T01:00:00Z",
  },
  // WTA Matches
  {
    p1: "Aryna Sabalenka",
    p2: "Paula Badosa",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-10T18:00:00Z",
  },
  {
    p1: "Iga Swiatek",
    p2: "Anna Kalinskaya",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-10T20:00:00Z",
  },
  {
    p1: "Coco Gauff",
    p2: "Mirra Andreeva",
    tournament: "Indian Wells Masters",
    round: "R32",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-10T22:00:00Z",
  },
  {
    p1: "Elena Rybakina",
    p2: "Madison Keys",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-12T18:00:00Z",
  },
  {
    p1: "Jasmine Paolini",
    p2: "Ons Jabeur",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-12T20:00:00Z",
  },
  {
    p1: "Zheng Qinwen",
    p2: "Emma Navarro",
    tournament: "Indian Wells Masters",
    round: "R16",
    surface: "Hard",
    tour: "WTA",
    startTime: "2026-03-12T22:00:00Z",
  },
  // Completed matches (AO Results)
  {
    p1: "Jannik Sinner",
    p2: "Alexander Zverev",
    tournament: "Australian Open",
    round: "F",
    surface: "Hard",
    tour: "Grand Slam",
    startTime: "2026-01-26T08:30:00Z",
    winner: "Jannik Sinner",
    score: "6-3 7-6(4) 6-3",
    status: "completed",
  },
  {
    p1: "Carlos Alcaraz",
    p2: "Novak Djokovic",
    tournament: "Australian Open",
    round: "SF",
    surface: "Hard",
    tour: "Grand Slam",
    startTime: "2026-01-24T08:30:00Z",
    winner: "Carlos Alcaraz",
    score: "6-4 6-3 7-5",
    status: "completed",
  },
  {
    p1: "Jannik Sinner",
    p2: "Ben Shelton",
    tournament: "Australian Open",
    round: "SF",
    surface: "Hard",
    tour: "Grand Slam",
    startTime: "2026-01-24T03:30:00Z",
    winner: "Jannik Sinner",
    score: "7-6(2) 6-2 6-2",
    status: "completed",
  },
  {
    p1: "Aryna Sabalenka",
    p2: "Madison Keys",
    tournament: "Australian Open",
    round: "F",
    surface: "Hard",
    tour: "Grand Slam",
    startTime: "2026-01-25T08:30:00Z",
    winner: "Aryna Sabalenka",
    score: "6-1 6-2",
    status: "completed",
  },
  {
    p1: "Iga Swiatek",
    p2: "Coco Gauff",
    tournament: "Australian Open",
    round: "SF",
    surface: "Hard",
    tour: "Grand Slam",
    startTime: "2026-01-23T08:30:00Z",
    winner: "Coco Gauff",
    score: "4-6 7-5 6-3",
    status: "completed",
  },
];

export const h2hData = [
  { p1: "Jannik Sinner", p2: "Alexander Zverev", p1Wins: 4, p2Wins: 2 },
  { p1: "Jannik Sinner", p2: "Carlos Alcaraz", p1Wins: 4, p2Wins: 6 },
  { p1: "Jannik Sinner", p2: "Novak Djokovic", p1Wins: 4, p2Wins: 7 },
  { p1: "Jannik Sinner", p2: "Daniil Medvedev", p1Wins: 7, p2Wins: 6 },
  { p1: "Carlos Alcaraz", p2: "Novak Djokovic", p1Wins: 5, p2Wins: 4 },
  { p1: "Carlos Alcaraz", p2: "Alexander Zverev", p1Wins: 5, p2Wins: 3 },
  { p1: "Novak Djokovic", p2: "Alexander Zverev", p1Wins: 8, p2Wins: 4 },
  { p1: "Novak Djokovic", p2: "Daniil Medvedev", p1Wins: 12, p2Wins: 5 },
  { p1: "Aryna Sabalenka", p2: "Iga Swiatek", p1Wins: 6, p2Wins: 7 },
  { p1: "Aryna Sabalenka", p2: "Coco Gauff", p1Wins: 4, p2Wins: 1 },
  { p1: "Iga Swiatek", p2: "Coco Gauff", p1Wins: 5, p2Wins: 2 },
  { p1: "Elena Rybakina", p2: "Aryna Sabalenka", p1Wins: 3, p2Wins: 5 },
];
